"""
Heatmap utilities for FIDTM point-based crowd visualization.

This module converts localized head points into smooth heatmaps.

The heatmap is generated by:
    1. placing impulses at detected point locations
    2. applying Gaussian blur
    3. normalizing to 0-255
    4. applying OpenCV COLORMAP_JET

Outputs:
    - heatmap color image
    - heatmap overlay on original frame
    - heatmap-only visualization
"""

from __future__ import annotations

from typing import Iterable

import cv2
import numpy as np


Point = tuple[float, float, float]


def make_smooth_heatmap_from_points(
    frame_shape: tuple[int, int, int] | tuple[int, int],
    points: Iterable[Point],
    sigma: float = 35.0,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Create a smooth heatmap from localized points.

    Args:
        frame_shape: Shape of original frame, usually frame.shape.
        points: Iterable of points as (x, y, score).
        sigma: Gaussian blur sigma. Higher value creates smoother heatmap.

    Returns:
        heat_color: BGR heatmap image using COLORMAP_JET.
        heat_uint8: Grayscale normalized heatmap from 0 to 255.
    """
    height, width = frame_shape[:2]

    heat = np.zeros((height, width), dtype=np.float32)

    for x, y, score in points:
        xi = int(round(x))
        yi = int(round(y))

        if 0 <= xi < width and 0 <= yi < height:
            heat[yi, xi] += 1.0

    heat = cv2.GaussianBlur(
        heat,
        ksize=(0, 0),
        sigmaX=sigma,
        sigmaY=sigma,
    )

    if heat.max() > 0:
        heat = heat / heat.max()

    heat_uint8 = np.uint8(255 * heat)
    heat_color = cv2.applyColorMap(heat_uint8, cv2.COLORMAP_JET)

    return heat_color, heat_uint8


def draw_points_on_frame(
    frame_bgr: np.ndarray,
    points: Iterable[Point],
    radius: int = 4,
    point_color: tuple[int, int, int] = (0, 255, 0),
    outline_color: tuple[int, int, int] = (0, 0, 0),
) -> np.ndarray:
    """
    Draw localized FIDTM points on a frame.

    Args:
        frame_bgr: Input frame.
        points: Points as (x, y, score).
        radius: Circle radius.
        point_color: BGR color for filled point.
        outline_color: BGR color for circle outline.

    Returns:
        Annotated frame.
    """
    out = frame_bgr.copy()

    for x, y, score in points:
        xi = int(round(x))
        yi = int(round(y))

        cv2.circle(out, (xi, yi), radius, point_color, -1)
        cv2.circle(out, (xi, yi), radius + 3, outline_color, 1)

    return out


def draw_heatmap_overlay(
    frame_bgr: np.ndarray,
    points: Iterable[Point],
    count: int | None = None,
    sigma: float = 35.0,
    draw_points: bool = True,
    frame_alpha: float = 0.60,
    heatmap_alpha: float = 0.40,
) -> np.ndarray:
    """
    Draw heatmap overlay on top of the original video frame.

    Args:
        frame_bgr: Original BGR frame.
        points: FIDTM points as (x, y, score).
        count: Optional total count to write on frame.
        sigma: Gaussian heatmap smoothing.
        draw_points: Whether to draw localization points on top.
        frame_alpha: Original frame blending weight.
        heatmap_alpha: Heatmap blending weight.

    Returns:
        BGR visualization frame.
    """
    points = list(points)

    heat_color, _ = make_smooth_heatmap_from_points(
        frame_shape=frame_bgr.shape,
        points=points,
        sigma=sigma,
    )

    overlay = cv2.addWeighted(
        frame_bgr,
        frame_alpha,
        heat_color,
        heatmap_alpha,
        0,
    )

    if draw_points:
        overlay = draw_points_on_frame(
            overlay,
            points,
            radius=4,
            point_color=(0, 255, 0),
            outline_color=(0, 0, 0),
        )

    cv2.rectangle(overlay, (20, 20), (700, 100), (0, 0, 0), -1)

    if count is None:
        title = "FIDTM Heatmap + Localization"
    else:
        title = f"FIDTM Heatmap + Localization | Count: {count}"

    cv2.putText(
        overlay,
        title,
        (35, 60),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )

    return overlay


def draw_heatmap_only(
    frame_bgr: np.ndarray,
    points: Iterable[Point],
    count: int | None = None,
    sigma: float = 35.0,
    draw_points: bool = True,
) -> np.ndarray:
    """
    Draw heatmap only, without the original video background.

    Args:
        frame_bgr: Original frame. Used only for frame shape.
        points: FIDTM points as (x, y, score).
        count: Optional total count to write on frame.
        sigma: Gaussian heatmap smoothing.
        draw_points: Whether to draw points on the heatmap.

    Returns:
        BGR heatmap-only visualization.
    """
    points = list(points)

    heat_color, _ = make_smooth_heatmap_from_points(
        frame_shape=frame_bgr.shape,
        points=points,
        sigma=sigma,
    )

    out = heat_color.copy()

    if draw_points:
        for x, y, score in points:
            xi = int(round(x))
            yi = int(round(y))

            cv2.circle(out, (xi, yi), 3, (255, 255, 255), -1)
            cv2.circle(out, (xi, yi), 6, (0, 0, 0), 1)

    cv2.rectangle(out, (20, 20), (700, 100), (0, 0, 0), -1)

    if count is None:
        title = "FIDTM Heatmap Only + Points"
    else:
        title = f"FIDTM Heatmap Only + Points | Count: {count}"

    cv2.putText(
        out,
        title,
        (35, 60),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )

    return out